# Define constants and URLs
PROPERTY_IDS_URL = "https://subastas.boe.es/reg/subastas_ava.php?accion=Mas&id_busqueda=_Y0wyY1ppR3hqa2xCZjhyNDREcndPME1hRHdnbXJaWkV4ME9mbW5XN0RIekkyMkpHdGErVHNZYURoUjViSlJua0JMQzltMS9nVXNUMjlFa1VBbG4yT2hoSGNEUGw5WjhoaGZtQzQrSHJGVTFqS2RUODJkL0RaMUxGSEpwemhPeU5DL1o3aW1NYmVpVG93S3d6UHAzWXNXS0c3VWlsQTBuRU9zL0FjQW1jSGRnamEzTFU2aERSUzVFZDBmS0NLNjljeTZOanZNWWxjNEVoZHZhc2pwU2hKZUJGTEg1T3ViREVLTGhlRXp4MjZXZHhjWkN2YmcxQ0NXNHNxNExJVmYrSGFaSDdoRU0xL0Q2OE9VR1R2c2ZSOEE9PQ,,-0-450"
PROPERTY_BIENES_URL = "https://subastas.boe.es/reg/detalleSubasta.php?idSub={property_id}&ver=3&idBus=_Y0wyY1ppR3hqa2xCZjhyNDREcndPME1hRHdnbXJaWkV4ME9mbW5XN0RIekkyMkpHdGErVHNZYURoUjViSlJua0JMQzltMS9nVXNUMjlFa1VBbG4yT2hoSGNEUGw5WjhoaGZtQzQrSHJGVTFqS2RUODJkL0RaMUxGSEpwemhPeU5DL1o3aW1NYmVpVG93S3d6UHAzWXNXS0c3VWlsQTBuRU9zL0FjQW1jSGRnamEzTFU2aERSUzVFZDBmS0NLNjljeTZOanZNWWxjNEVoZHZhc2pwU2hKZUJGTEg1T3ViREVLTGhlRXp4MjZXZHhjWkN2YmcxQ0NXNHNxNExJVmYrSGFaSDdoRU0xL0Q2OE9VR1R2c2ZSOEE9PQ,,-0-450&idLote=&numPagBus="

PROPERTY_PRUEBA = "https://subastas.boe.es/reg/subastas_ava.php?accion=Mas&id_busqueda=_aGZaODZVK09aRlgzcFpxSzQ4SWlXa3ZOSDdnaFNaMkg1OWV0U2pHWjFwUEc2aHo5TVl3QjNtUnJUQ1FGS2ZoYmdoYS94cncxU1ZhYjNYMXFndzdyaVNvUlZpSUJHdm83eEVla3UyMElJYjJFcHpGdFB4N0RWQ20xRThPNFFrUStieGtWOWhaTlJuNGtqUXlyV3V3dFdYbWFPd3BGMnh3dlZaK2tXaElFQjVvZmhiUkdFMTJJYTYrUnRsMkU0enNHektmOUZRdnpYQmZHcERYRlY2bUdDVHE1UFZaLzJRS1BDMFlPNVhCb2R1SEYrOGljOW85djdqdE1zeWZySnNZQS8wTkhSS1lvWkxVMGJ5enJkWUhLdEhmYy9JY3g0YlF3YnpZdWo1aVhlOGs9-0-50"

BIENES_PRUEBA = "https://subastas.boe.es/reg/detalleSubasta.php?idSub={property_id}&ver=3&idBus=_aGZaODZVK09aRlgzcFpxSzQ4SWlXa3ZOSDdnaFNaMkg1OWV0U2pHWjFwUEc2aHo5TVl3QjNtUnJUQ1FGS2ZoYmdoYS94cncxU1ZhYjNYMXFndzdyaVNvUlZpSUJHdm83eEVla3UyMElJYjJFcHpGdFB4N0RWQ20xRThPNFFrUStieGtWOWhaTlJuNGtqUXlyV3V3dFdYbWFPd3BGMnh3dlZaK2tXaElFQjVvZmhiUkdFMTJJYTYrUnRsMkU0enNHektmOUZRdnpYQmZHcERYRlY2bUdDVHE1UFZaLzJRS1BDMFlPNVhCb2R1SEYrOGljOW85djdqdE1zeWZySnNZQS8wTkhSS1lvWkxVMGJ5enJkWUhLdEhmYy9JY3g0YlF3YnpZdWo1aVhlOGs9-0-50&idLote=&numPagBus="

WORDS_TO_FILTER = [
    'LG', 'TN', 'PEBRES', 'VIVIENDA', 'CP', 'MN', '30005', 'PD', 'AR', 'CN',
    'GREGORIO', 'NUEVA', 'POU', 'RAMON', 'PARAJE', 'PARTIDA', 'DISEMINADO',
    'SAN', 'PEREIJO.', 'SANTA', 'CAÑOCLAR', 'NO', 'CLOSA', 'GRAN', 'LA', 'SUERTE'
]

STANDARDIZED_MAPPING = {
    'CL': 'CALLE',
    'LUGAR': 'LUGAR',
    'CAMINO': 'CAMINO',
    'CALLE': 'CALLE',
    'AV.': 'AVENIDA',
    'CL.': 'CALLE',
    'C/': 'CALLE',
    'C/COSTERETA,': 'CALLE COSTERETA',
    'UR': 'URBANIZACION',
    'C.': 'CALLE',
    'CM': 'CAMINO',
    'CR': 'CALLE',
    'C/SANTIAGO': 'CALLE SANTIAGO',
    'PA': 'PASAJE',
    'CARRETERA': 'CARRETERA',
    'AV': 'AVENIDA',
    'PJ': 'PASAJE',
    'C/VIRGEN': 'CALLE VIRGEN',
    'CALLE:': 'CALLE',
    'PARQUE': 'PARQUE',
    'PZ': 'PLAZA',
    'POLIGONO': 'POLIGONO',
    'PG': 'POLIGONO',
    'POLÍGONO': 'POLIGONO',
    'PLAZA': 'PLAZA',
    'C/BLASCO': 'CALLE BLASCO',
    'PASAJE': 'PASAJE',
    'C/CHILE': 'CALLE CHILE',
    'C/TEIDE': 'CALLE TEIDE',
    'C/ALFONSO': 'CALLE ALFONSO',
    '"EDIFICIO': 'EDIFICIO',
    'CL/': 'CALLE',
    'AVENIDA': 'AVENIDA',
    'NUMERO': 'NUMERO',
    'URB.': 'URBANIZACION',
    'C/ANTONIO': 'CALLE ANTONIO',
    'URB': 'URBANIZACION',
    'RONDA': 'RONDA',
    'RAMBLA': 'RAMBLA',
    'URBANIZACION': 'URBANIZACION',
    'C/LUÍS': 'CALLE LUIS',
    'C/NICOLÁS': 'CALLE NICOLAS',
    'PG.': 'POLIGONO',
    'AVDA': 'AVENIDA',
    'TRAVESIA': 'TRAVESIA',
    'RAMAL': 'RAMAL',
    'CTRA': 'CARRETERA',
    'PASEO': 'PASEO',
    'SOLAR': 'SOLAR',
    'CAMI': 'CAMINO',
    'C/SANTO': 'CALLE SANTO',
    'AVD': 'AVENIDA',
    'PARCELA': 'PARCELA',
    'AVDA.': 'AVENIDA'
}
